before_script: gem update --system 2.4.0
bundler_args: --without development
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2
  fast_finish: true
sudo: false
