name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rake:
    runs-on: ubuntu-latest
    env:
      SHARE: ${{ github.ref_name == 'main' && '1' || '' }}

    strategy:
      matrix:
        ruby-version: ['3.1', '3.0', '2.7', '2.5.1',  '2.4.3',  '2.3.0',
                       '2.1.9',  '2.2.10', 'ruby-head', 'jruby-9.1.17.0',
                       'jruby-head']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run benchmarks
        run: bundle exec rake
